"""Render ``DRIFT_REPORT.md`` (ranked, tracked) and one file per finding under
``graphify-out/drift/`` (gitignored, Windows-safe names)."""
from __future__ import annotations

import datetime as _dt
from pathlib import Path
from typing import List

from .canon import ROOT
from .detect import Finding
from .fsnames import safe_filename

_REPORT = ROOT / "DRIFT_REPORT.md"
_FINDINGS_DIR = ROOT / "graphify-out" / "drift" / "findings"

_HEADER = """# DRIFT_REPORT.md

Business-definition drift across code, SQL, docs, ADRs, and the agent system prompt.
Generated by `python -m scripts.drift` — do not hand-edit.

| | |
|---|---|
| **Generated** | {date} |
| **Surfaces scanned** | {surfaces} |
| **Findings** | {n} ({auto} auto-fixable, {human} needs-human) |
| **Sibling** | [`docs/audits/sql-consistency.md`](docs/audits/sql-consistency.md) — deeper, SQL-only, 3 rules |

## Source-of-truth hierarchy

1. `config/settings.py` — `STATUS_*` base tuples + derived sets, `PRIMEIRA_PARCELA`,
   `PORTFOLIO_COLUMN`, `BOLETO_PAGO_PRAZO_SQL`, both agent filters, `RISK_LEVEL_*`.
2. `agecob-lens/docs/regras/id-rec-status.md` — status enum narrative.
3. `agecob-lens/docs/data-layer.md` — CPC funnel, conversão, dedup, date window.
4. `docs/data-dictionary.md` — column names + code enumerations.
5. `dominios/agente/metric_registry.json` — generated from (1), guarded by `tests/test_metric_registry.py`.

Everything else is a **consumer** and must match the above.
"""

_FOOTER = """
## What this run checked

For every canonical definition, every consumer surface is scanned for: the literal
tuple, near-miss tuples (subset/superset), the prose form, the formula form, and
retired tokens (`CPC_COMPLEMENTO_IDS`, bare `CONTATO = 1`, `COD_COMPLEMENTO IN`).
Plus four cross-surface checks: Python vs SQL excluded-agent lists, superseded-ADR
references, `metric_registry.json` citation staleness, and frontend status literals
with no link to the backend.

## Coverage / limits

- Skipped: `node_modules`, `dist`, `graphify-out`, `entrega-api/` is tier `fork`.
- `historical` tier (`plans/`, `handoffs/`, `archive/`, `*.original.md`) is scanned but
  ranked low.
- No SQL executed — semantic equivalence of query variants is not verified against the live schema.
- Blast `reach` uses `graphify-out/graph.json` in-edges when present, else a tier + fan-out heuristic.
"""


def write_report(findings: List[Finding], surface_count: int) -> Path:
    auto = [f for f in findings if f.fix_class == "auto"]
    human = [f for f in findings if f.fix_class == "human"]
    parts = [_HEADER.format(
        date=_dt.date.today().isoformat(), surfaces=surface_count,
        n=len(findings), auto=len(auto), human=len(human),
    )]
    parts.append(_rank_table(findings))
    parts.append("\n## Findings — detail\n")
    for rank, f in enumerate(findings, 1):
        parts.append(_detail(rank, f))
    parts.append(_classification(auto, human))
    parts.append(_FOOTER)
    text = "\n".join(parts)
    _REPORT.write_text(text, encoding="utf-8")
    _write_finding_files(findings)
    return _REPORT


def _rank_table(findings: List[Finding]) -> str:
    rows = ["\n## Ranked by blast radius\n",
            "| # | Definition | Where | Kind | Class | Blast |",
            "|--:|---|---|---|---|--:|"]
    for i, f in enumerate(findings, 1):
        rows.append("| {} | `{}` | `{}:{}` | {} | {} | **{}** |".format(
            i, f.def_key, f.path, f.line, f.kind, f.fix_class, f.blast))
    return "\n".join(rows)


def _detail(rank: int, f: Finding) -> str:
    return (
        "### {rank}. `{key}` in `{path}:{line}` · {cls} · blast {blast}\n\n"
        "- **Canonical:** `{canon}`\n"
        "- **Found:** `{found}` — {kind}, surface tier `{tier}`\n"
        "- **Why it matters:** {why}\n"
        "- **Line:** `{excerpt}`\n"
    ).format(
        rank=rank, key=f.def_key, path=f.path, line=f.line, cls=f.fix_class, blast=f.blast,
        canon=f.canonical, tier=f.tier, found=f.found, kind=f.kind, why=f.why,
        excerpt=f.excerpt.replace("`", "'"),
    )


def _classification(auto: List[Finding], human: List[Finding]) -> str:
    def _list(items: List[Finding]) -> str:
        return "\n".join("- `{}` — `{}:{}`".format(f.def_key, f.path, f.line) for f in items) or "- (none)"
    return (
        "\n## Classification\n\n"
        "### auto-fixable ({}) — stale consumer text; canonical source unambiguous\n{}\n\n"
        "### needs-human ({}) — a business or architecture decision\n{}\n"
    ).format(len(auto), _list(auto), len(human), _list(human))


def _write_finding_files(findings: List[Finding]) -> None:
    _FINDINGS_DIR.mkdir(parents=True, exist_ok=True)
    taken: set = set()
    for rank, f in enumerate(findings, 1):
        stem = Path(f.path).stem
        name = safe_filename("{:02d} {} {} L{}".format(rank, f.def_key, stem, f.line))
        taken.add(name.lower())
        body = (
            "---\nfinding: {key}\npath: {path}\nline: {line}\nkind: {kind}\n"
            "class: {cls}\nblast: {blast}\n---\n\n"
            "**Canonical:** `{canon}`\n\n**Found:** `{found}`\n\n{why}\n\n`{excerpt}`\n"
        ).format(key=f.def_key, path=f.path, line=f.line, kind=f.kind, cls=f.fix_class,
                 blast=f.blast, canon=f.canonical, found=f.found, why=f.why,
                 excerpt=f.excerpt.replace("`", "'"))
        (_FINDINGS_DIR / name).write_text(body, encoding="utf-8")
